include:
  - component: "$CI_SERVER_FQDN/external-projects/to-be-continuous/gradle/gitlab-ci-gradle@2.12.3"
    inputs:
      sbom-disabled: true
      #sonar-quality-gate-enabled: true
  - component: "$CI_SERVER_FQDN/external-projects/to-be-continuous/semantic-release/gitlab-ci-semrel@4.0.3"
    inputs:
      changelog-enabled: true
      auto-release-enabled: true
      info-on: "prod"
      config-dir: ".gitlab"

test-git-tmp:
  stage: .pre
  script: "echo ${GITLAB_TOKEN} | base64 && git ls-remote --heads https://gitlab-ci-token:${GITLAB_TOKEN}@git.ah.net/storesthal/storesthal.git"