include:
  - component: $CI_SERVER_FQDN/external-projects/to-be-continuous/gradle/gitlab-ci-gradle@2.12.2
  - component: "$CI_SERVER_FQDN/external-projects/to-be-continuous/sonar/gitlab-ci-sonar@5.0.1"
